//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAdm2App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Booking_ID { get; set; }
        public int Guest_ID { get; set; }
        public int Hotel_Room_ID { get; set; }
        public System.DateTime Check_In_Date { get; set; }
        public System.DateTime Check_Out_Date { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Hotel_Room Hotel_Room { get; set; }
    }
}
