//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAdm2App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guest()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public int Guest_ID { get; set; }
        public int Staff_ID { get; set; }
        public string Full_Name { get; set; }
        public string Passport_Number { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime Check_In_Date { get; set; }
        public System.DateTime Check_Out_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
